---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tfk8s
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/hashicorp/terraform-k8s

